jobs:
  # Build the docker image and run tests.
  build_and_test:
    executor: heroku/default
    steps:
      # For using docker commands.
      - setup_remote_docker

      # Build the docker image
      - checkout
      - run: docker build -t densenet-inference-heroku .

      # Run tests.
      - run:
          command: docker run densenet-inference-heroku pytest

  # Build the docker image and deploy it to Heroku.
  build_and_deploy:
    executor: heroku/default
    steps:
      # For using docker commands.
      - setup_remote_docker

      # Build the docker image
      - checkout
      - run: docker build .

      # Deploy to Heroku
      - heroku/install
      - run: heroku container:login
      - heroku/check-authentication
      - heroku/push-docker-image:
          process-types: web
          app-name: "densenet-demo-app-circleci"
      - heroku/release-docker-image:
          process-types: web
          app-name: "densenet-demo-app-circleci"

orbs:
  # For using Heroku CLI commandｓ.
  heroku: circleci/heroku@2.0

version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build_and_deploy